In [2]:
import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2

In [3]:
data = pd.read_csv('bank-additional-full.csv',sep=';')

In [4]:
new_data = data.copy()

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null object
dtypes: float64(5), int64(5), object(11)
memory usa

In [6]:
data.describe()

age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000   
mean      40.02406    258.285010      2.567593    962.475454      0.172963   
std       10.42125    259.279249      2.770014    186.910907      0.494901   
min       17.00000      0.000000      1.000000      0.000000      0.000000   
25%       32.00000    102.000000      1.000000    999.000000      0.000000   
50%       38.00000    180.000000      2.000000    999.000000      0.000000   
75%       47.00000    319.000000      3.000000    999.000000      0.000000   
max       98.00000   4918.000000     56.000000    999.000000      7.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  41188.000000    41188.000000   41188.000000  41188.000000  41188.000000  
mean       0.081886       93.575664     -40.502600      3.621291   5167.035911  
std        1.570960        0.578840       4.628198      1.734447     72.251528  
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000  
25%       -1.800000       93.075000     -42.700000      1.344000   5099.100000  
50%        1.100000       93.749000     -41.800000      4.857000   5191.000000  
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000  
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

In [7]:
np.unique(data.poutcome, return_counts = True)

(array(['failure', 'nonexistent', 'success'], dtype=object),
 array([ 4252, 35563,  1373]))

In [8]:
data.y.unique()

array(['no', 'yes'], dtype=object)

In [9]:
## one hot encoding

In [10]:
new_data.y[new_data.y == 'yes'] = 1 # convery label column to int
new_data.y[new_data.y == 'no'] = 0 # convery label column to int


/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [11]:
new_data = new_data.astype({'y':'int64'})

In [12]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null int64
dtypes: float64(5), int64(6), object(10)
memory usag

In [13]:
new_data_df = pd.get_dummies(new_data, columns=['job','marital','education','day_of_week','default','housing','loan',
                                 'contact','month','poutcome'], drop_first=True)

In [14]:
new_X = new_data_df.loc[:,  new_data_df.columns != 'y'] # select X

In [15]:
new_y = new_data_df.y
new_X

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
5       45       198         1    999         0           1.1          93.994   
6       59       139         1    999         0           1.1          93.994   
7       41       217         1    999         0           1.1          93.994   
8       24       380         1    999         0           1.1          93.994   
9       25        50         1    999         0           1.1          93.994   
10      41        55         1    999         0           1.1          93.994   
11      25       222         1    999         0           1.1          93.994   
12      29       137         1    999         0           1.1          93.994   
13      57       293         1    999         0           1.1          93.994   
14      35       146         1    999         0           1.1          93.994   
15      54       174         1    999         0           1.1          93.994   
16      35       312         1    999         0           1.1          93.994   
17      46       440         1    999         0           1.1          93.994   
18      50       353         1    999         0           1.1          93.994   
19      39       195         1    999         0           1.1          93.994   
20      30        38         1    999         0           1.1          93.994   
21      55       262         1    999         0           1.1          93.994   
22      55       342         1    999         0           1.1          93.994   
23      41       181         1    999         0           1.1          93.994   
24      37       172         1    999         0           1.1          93.994   
25      35        99         1    999         0           1.1          93.994   
26      59        93         1    999         0           1.1          93.994   
27      39       233         1    999         0           1.1          93.994   
28      54       255         2    999         0           1.1          93.994   
29      55       362         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41158   35       363         1    999         0          -1.1          94.767   
41159   35       514         1      9         4          -1.1          94.767   
41160   33       843         1    999         0          -1.1          94.767   
41161   33       510         1    999         1          -1.1          94.767   
41162   60       347         2      4         1          -1.1          94.767   
41163   35       385         3      4         2          -1.1          94.767   
41164   54      1868         2     10         1          -1.1          94.767   
41165   38       403         2    999         0          -1.1          94.767   
41166   32       651         1    999         1          -1.1          94.767   
41167   32       236         3    999         0          -1.1          94.767   
41168   38       144         2    999         0          -1.1          94.767   
41169   62       154         5    999         0          -1.1          94.767   
41170   40       293         2    999         4          -1.1          94.767   
41171   33       112         1    999         0          -1.1          94.767   
41172   31       353         1    999         0          -1.1          94.767   
41173   62       329         1    999         2          -1.1          94.767   
41174   62       208         1      1         6          -1.1          94.767   
41175   34       180         1    999 

In [16]:
new_X.values

array([[ 56., 261.,   1., ...,   0.,   1.,   0.],
       [ 57., 149.,   1., ...,   0.,   1.,   0.],
       [ 37., 226.,   1., ...,   0.,   1.,   0.],
       ...,
       [ 56., 189.,   2., ...,   0.,   1.,   0.],
       [ 44., 442.,   1., ...,   0.,   1.,   0.],
       [ 74., 239.,   3., ...,   0.,   0.,   0.]])

## train test split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(new_X.values,new_y.values,test_size=0.2,random_state=0)

##  resample

In [21]:
!pip install imblearn

     |████████████████████████████████| 163kB 9.2MB/s eta 0:00:01
You should consider upgrading via the 'pip install --upgrade pip' command.


In [22]:
from imblearn.over_sampling import SMOTE

Using TensorFlow backend.


In [23]:
sm = SMOTE(random_state=12, sampling_strategy = 1)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [24]:
np.unique(y_train_res, return_counts = True) # oversampling

(array([0, 1]), array([29229, 29229]))

## Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score

In [26]:
logistic_model = LogisticRegression(max_iter= 100,random_state=0)

In [27]:
logistic_model.fit(X_train_res,y_train_res)

/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [128]:
logistic_model.score(X_train_res,y_train_res)

0.8644667966745355

In [28]:
pred = logistic_model.predict(X_test)
print(f"accuracy = {logistic_model.score(X_test, y_test)}")
print(f"r2 = {r2_score(y_test, pred)}")
print(f"f1 = {f1_score(y_test,pred)}")

accuracy = 0.8590677348871085
r2 = -0.4219579341023798
f1 = 0.5825242718446603


In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
tn, fp, fn, tp = confusion_matrix(y_test, pred).ravel()
print(np.array([[tp, fn], [fp, tn]]))

[[ 810  109]
 [1052 6267]]


In [31]:
print("precision:{precision}, recall:{recall}".format(precision = tp/(tp+fp),recall = tp/(tp+fn)))

precision:0.43501611170784105, recall:0.8813928182807399


## Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rf = RandomForestClassifier(n_estimators = 5000, max_depth = 6, min_samples_split = 3, random_state=0)

In [34]:
rf.fit(X_train_res,y_train_res)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=6, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, n_estimators=5000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [35]:
rf_pred = rf.predict(X_test)
print(f"accuracy = {rf.score(X_test, y_test)}")
print(f"r2 = {r2_score(y_test, rf_pred)}")
print(f"f1 = {f1_score(y_test,rf_pred)}")

accuracy = 0.8782471473658655
r2 = -0.22844427898767172
f1 = 0.5700814402057436


In [36]:
tn, fp, fn, tp = confusion_matrix(y_test, rf_pred).ravel()
print(np.array([[tp, fn], [fp, tn]]))

[[ 665  254]
 [ 749 6570]]


In [37]:
print("precision:{precision}, recall:{recall}".format(precision = tp/(tp+fp),recall = tp/(tp+fn)))

precision:0.47029702970297027, recall:0.7236126224156693


## Gradient Boosting

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

In [39]:
gdb_model = GradientBoostingClassifier(learning_rate = 0.05,random_state=0)

In [40]:
gdb_model.fit(X_train_res,y_train_res)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.05, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [41]:
gdb_pred = gdb_model.predict(X_test)
print(f"accuracy = {gdb_model.score(X_test, y_test)}")
print(f"r2 = {r2_score(y_test, gdb_pred)}")
print(f"f1 = {f1_score(y_test,gdb_pred)}")

accuracy = 0.9016751638747269
r2 = 0.007936325044851311
f1 = 0.6437994722955145


In [42]:
tn, fp, fn, tp = confusion_matrix(y_test, gdb_pred).ravel()
print(np.array([[tp, fn], [fp, tn]]))

[[ 732  187]
 [ 623 6696]]


In [43]:
print("precision:{precision}, recall:{recall}".format(precision = tp/(tp+fp),recall = tp/(tp+fn)))

precision:0.5402214022140222, recall:0.7965179542981502


## XGboosting

In [44]:
from xgboost import XGBClassifier

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
xgb_model = XGBClassifier()

In [ ]:
xgb_model.fit(X_train_res,y_train_res)

In [ ]:
xgb_pred = xgb_model.predict(X_test)
print(f"accuracy = {xgb_model.score(X_test, y_test)}")
print(f"r2 = {r2_score(y_test, xgb_pred)}")
print(f"f1 = {f1_score(y_test,xgb_pred)}")

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_test, xgb_pred).ravel()
print(np.array([[tp, fn], [fp, tn]]))

In [ ]:
print("precision:{precision}, recall:{recall}".format(precision = tp/(tp+fp),recall = tp/(tp+fn)))

## Neural Network

In [45]:
import tensorflow as tf
from tensorflow.keras import layers
keras = tf.keras


In [119]:
nn_model = tf.keras.models.Sequential()

In [120]:
nn_model.add(keras.layers.Dense(units=100, input_dim=53,activation='relu'))
nn_model.add(keras.layers.Dense(units=50, activation='relu'))
nn_model.add(keras.layers.Dense(units=20, activation='relu'))

In [121]:
nn_model.add(keras.layers.Dense(units=1,activation='sigmoid'))

In [122]:
nn_model.compile(loss='binary_crossentropy',
              optimizer='adam',
                metrics=['accuracy'])

In [123]:
nn_model.fit(X_train_res, y_train_res, epochs=10, batch_size=32)


Train on 58458 samples
Epoch 1/10
58458/58458 [==============================] - 8s 132us/sample - loss: 2.3303 - acc: 0.7515
Epoch 2/10
58458/58458 [==============================] - 7s 127us/sample - loss: 1.0900 - acc: 0.7906
Epoch 3/10
58458/58458 [==============================] - 7s 128us/sample - loss: 0.6739 - acc: 0.8104
Epoch 4/10
58458/58458 [==============================] - 7s 127us/sample - loss: 0.4849 - acc: 0.8277
Epoch 5/10
58458/58458 [==============================] - 7s 128us/sample - loss: 0.4468 - acc: 0.8325
Epoch 6/10
58458/58458 [==============================] - 7s 127us/sample - loss: 0.3713 - acc: 0.8518
Epoch 7/10
58458/58458 [==============================] - 7s 127us/sample - loss: 0.3507 - acc: 0.8576
Epoch 8/10
58458/58458 [==============================] - 7s 127us/sample - loss: 0.3345 - acc: 0.8648
Epoch 9/10
58458/58458 [==============================] - 7s 128us/sample - loss: 0.3255 - acc: 0.8676
Epoch 10/10
58458/58458 [=========================

In [124]:
nn_model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 100)               5400      
_________________________________________________________________
dense_27 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_28 (Dense)             (None, 20)                1020      
_________________________________________________________________
dense_29 (Dense)             (None, 1)                 21        
Total params: 11,491
Trainable params: 11,491
Non-trainable params: 0
_________________________________________________________________


In [104]:
X_train_res

TypeError: 'tuple' object is not callable